---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: micro-java
    provider: jkube
    version: "1.0"
    group: com.redhat.training.openshift.hello
  name: configmap-hello
data:
  APP_MSG: the is the new value that hhas been set.
